// ===== src/texts/texts-main.js · 界面与按钮文案 =====
export const UI_TEXTS = {
  appName: '浮生牌',
  step1: '第一步 · 起念',
  step2: '第二步 · 立极',
  step3: '第三步 · 观象',
  labelTi: '你',
  labelYong: '所问之事',
  labelSeparator: '⚡',
  labelEmpty: '空',
  labelDiffPrefix: '差',
  placeholderQuestion: '默念你的问题（可不填）',
  placeholderImport: '粘贴分享码',
  placeholderFollowUp: '追问或补充信息',
  btnStartDraw: '抽牌',
  btnManual: '手动录入',
  btnLazy: '一键起局',
  btnConfirmTiYong: '布阵',
  btnInterpret: '生成解读',
  btnCopy: '复制',
  btnShareImage: '生成分享图',
  btnShareCode: '生成分享码',
  btnImport: '导入',
  btnDailyFortune: '今日状态',
  btnAIDeepRead: '深层解读',
  btnNewQuestion: '新问题',
  btnClose: '关闭',
  btnTestApi: '测试连接',
  btnSave: '保存',
  toastReset: '已重置，开始新的一局',
  toastCopied: '已复制到剪贴板',
  toastCopyFailed: '复制失败，请手动复制',
  toastJokersInjected: '大小王已加入牌局，可落位九宫',
  toastGridCleared: '九宫已清空',
  toastShareCodeCopied: '分享码已复制到剪贴板',
  toastImportSuccess: '导入成功',
  toastImportFail: '分享码无效或已过期',
  toastSaved: '已保存',
  toastProfileSaved: '个人资料已保存',
  toastCleared: '已清除',
  toastAnyCount: '牌已落位',
  toastLineConfirmed: '天机线已确认——你选中的这条线，就是本次的主线',
  toastLinesMultiple: '出现了多条天机线，选一条你最有感觉的',
  guideSelectTiYong: '从牌堆中选一张代表你的牌，再选一张代表所问之事的牌。',
  guideManual: '手动模式：拖动牌到九宫，或点击牌再点击宫位放置。',
  guideAfterTiYong: '将剩余牌放入九宫，每个宫位最多3张。差值反映能量状态。',
  apiStatusConfigured: '已配置',
  apiStatusNotConfigured: '未配置',
};

export const HISTORY_EMPTY = '还没有历史记录。开始一次占卜吧。';