// ===== src/texts/texts-main.js · 界面与按钮文案 =====
export const UI_TEXTS = {
  appName: '浮生牌',
  step1: '第一步 · 起念',
  step2: '选牌 · 你与所问之事',
  step3: '查看结果',
  labelTi: '你',
  labelYong: '所问之事',
  labelSeparator: '⚡',
  labelEmpty: '空',
  labelDiffPrefix: '差',
  placeholderQuestion: '默念你的问题（可不填）',
  placeholderImport: '粘贴分享码',
  placeholderFollowUp: '追问或补充信息',
  btnStartDraw: '抽牌',
  btnManual: '手动录入',
  btnLazy: '一键起局',
  btnConfirmTiYong: '放牌',
  btnInterpret: '生成解读',
  btnCopy: '复制',
  btnShareImage: '生成分享图',
  btnShareCode: '生成分享码',
  btnImport: '导入',
  btnDailyFortune: '今日状态',
  btnAIDeepRead: '深层解读',
  btnNewQuestion: '新问题',
  btnClose: '关闭',
  btnTestApi: '测试连接',
  btnSave: '保存',
  toastReset: '已重置，开始新的一局',
  toastCopied: '已复制到剪贴板',
  toastCopyFailed: '复制失败，请手动复制',
  toastJokersInjected: '大小王已加入牌局，可落位九宫',
  toastGridCleared: '九宫已清空',
  toastShareCodeCopied: '分享码已复制到剪贴板',
  toastImportSuccess: '导入成功',
  toastImportFail: '分享码无效或已过期',
  toastSaved: '已保存',
  toastProfileSaved: '个人资料已保存',
  toastCleared: '已清除',
  toastAnyCount: '牌已落位',
  toastLineConfirmed: '天机线已确认——你选中的这条线，就是本次的主线',
  toastLinesMultiple: '出现了多条天机线，选一条你最有感觉的',
  guideSelectTiYong: '从牌堆中选一张代表你的牌，再选一张代表所问之事的牌。',
  guideManual: '手动模式：拖动牌到九宫，或点击牌再点击宫位放置。',
  guideAfterTiYong: '将剩余牌放入九宫，每个宫位最多3张。差值反映能量状态。',
  apiStatusConfigured: '已配置',
  apiStatusNotConfigured: '未配置',
};

export const HISTORY_EMPTY = '还没有历史记录。开始一次占卜吧。';

// ===== 三句摘要词库（陪伴体 · 说人话 · 落在今天） =====
// 规则：不出现五行/天干/宫位等术语；只谈「此刻的我」和「今天可以怎么做」。

// ① 此刻的状态（情绪镜像）
export const STATUS_POOL = [
  '像一杯静置的水，表面平静，深处有沉淀。',
  '像刚点着的火苗，需要一点风，但不需要大风。',
  '像一棵春天的树，芽在长，只是你还看不见。',
  '像傍晚的云，飘着，但还不想下雨。',
  '像一杯热茶，还没凉，也没烫到端不住。',
  '像绕远路走回家的人，慢，但方向是对的。',
  '像刚醒来的早晨，睡意还在，光已经进来了。',
  '像一件晾着的衣服，还差一点风就干了。',
  '像慢下来的钟摆，不是停了，是在蓄力。',
  '像开了很多网页的手机，有点卡，清一清就好了。',
  '像温吞的天气，不算坏，但说不上好。',
  '像口袋里多出来的一颗糖，不急着吃，但知道它在。',
  '像半满的杯子，装得下，也还有余地。',
  '像雨后的街道，湿漉漉的，但空气是新的。',
];

// ② 一个提醒（落在「今天」，不吓人不命令）
export const REMINDER_POOL = [
  '今天适合安静一点，不是你的错，是风比较大。',
  '今天不用急着证明什么，先把手头的小事做完。',
  '今天别跟自己较劲，累了就换口气。',
  '今天不适合主动出击，适合整理和清理。',
  '今天的话不必说满，留一半给明天。',
  '今天适合守财，别冲动下单，手会痒但心会爽。',
  '今天别跟太强势的人硬刚，赢了也没意思。',
  '今天少看手机里别人的生活，多看自己的生活。',
  '今天心里有点堵是正常的，先让它待一会儿。',
  '今天把节奏放慢半拍，没人会扣你的分。',
  '今天不必对所有人都笑，对一个人好就够了。',
  '今天想休息就休息，那是恢复，不是偷懒。',
  '今天不适合做重大决定，先睡一觉再说。',
  '今天有人说话不好听，那是他的问题，不是你的。',
];

// ③ 一句建议 / 出口（可执行的下一步）
export const ACTION_POOL = [
  '把一直没做完的小事收尾，能量会自然流动。',
  '把最烦的一件事写在便签上，然后撕掉它。',
  '今天允许自己早睡，明天的事明天醒来说。',
  '今天允许自己拒绝一个不想去的邀约。',
  '给自己倒一杯热水，坐着喝完，什么都不想。',
  '找一个人，把一句憋了很久的话说掉一半。',
  '出门走十分钟，让身体先于脑子松下来。',
  '把手机调成勿扰，专心做一件手上的事。',
  '列一张三件事的小清单，做完就划掉。',
  '给自己买点好的，今天你值得一顿认真吃饭。',
  '给很久没联系的人发一句「最近好吗」。',
  '把房间一个角落收拾干净，心情会跟着清爽。',
  '今天允许自己吃顿好的，不为什么。',
  '把纠结的事写下来，左边是担心的，右边是能做的。',
];