// ===== src/state.js · 全局状态管理与 DOM 查询 =====
export const state = {
  question: '',
  category: '',
  deck: [],
  ti: null,
  yong: null,
  grid: {},
  line: null,
  lineOrder: {},
  step: 1,
  sel: null,
  possible: [],
  manualMode: false,
  gongOrder: [],
  chatHistory: [],
  selectedProvider: 'deepseek',
  uid: (function() { return Date.now() % 1000000; })(),
  editCount: 0,
  currentOnboardStep: 0,
  refinementTags: {},
  userCorpus: [],
  intent: null,
  fingerprint: null,
  entropyLevel: 0,
  chaosSeed: null,
  sealed: false,
  sealedAt: null,
  mode: 'simple',
  durianIndex: null,
  sealStatus: null,
  timeCapsule: null,
  loading: false,
};

export const $ = (sel) => document.querySelector(sel);
export const $$ = (sel) => document.querySelectorAll(sel);